companies:
  SAN.MC: Banco Santander
  BBVA.MC: BBVA
  ITX.MC: Inditex
  TEF.MC: Telefonica
  IBE.MC: Iberdrola
  REP.MC: Repsol
  FER.MC: Ferrovial
  ACS.MC: ACS
  AENA.MC: Aena
  CABK.MC: CaixaBank
  MAP.MC: Mapfre
  MTS.MC: ArcelorMittal
  SAB.MC: Banco Sabadell
  BKT.MC: Bankinter
  ANA.MC: Acciona
